# Generated by Django 3.0.14 on 2022-02-13 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20220213_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position']},
        ),
    ]
